version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.backend
    ports:
      - "8000:8000"
    environment:
      - AI_URL=http://ai-model:11434
      - USE_MOCK_AI=false
      - MODEL=qwen2.5:0.5b-instruct
    depends_on:
      - ai-model
    volumes:
      - ./data:/app/data
      - ./static:/app/static

  ai-model:
    image: ollama/ollama:latest
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    environment:
      - OLLAMA_HOST=0.0.0.0


volumes:
  ollama_data: